import { router } from "expo-router";
import { Text, View } from "react-native";

import {
    Brand,
    Button,
    Card,
    Notice,
    Screen,
} from "@/components/ui";

export default function VerifyEmailScreen() {
  return (
    <Screen centered>
      <View className="mx-auto w-full max-w-xl">
        <Brand />

        <Card>
          <Text className="text-3xl font-semibold text-ink">
            Verify your email
          </Text>

          <Text className="my-4 leading-6 text-muted">
            Email verification is not connected to the backend
            yet. No verification request or verification code
            has been generated by this application.
          </Text>

          <Notice
            tone="info"
            message="Backend integration pending"
          />

          <Button
            title="Continue to sign in"
            onPress={() => router.replace("/(auth)/login")}
          />
        </Card>
      </View>
    </Screen>
  );
}